[workspace]
resolver = "2"
members = [ "app",
    "sandboxdrv",
    "app"
]

[workspace.package]
edition = "2021"
publish = false
repository = "https://github.com/aCursedComrade/sandbox-research"
license = "MIT"

[profile.dev]
panic = "abort"
lto = true

[profile.release]
panic = "abort"
lto = true

[workspace.dependencies]
wdk = "0.2.0"
wdk-alloc = "0.2.0"
wdk-build = "0.2.0"
wdk-panic = "0.2.0"
wdk-sys = "0.2.0"
