[workspace]
resolver = "2"
members = ["frontend", "service", "driver"]

[workspace.package]
edition = "2021"
publish = false
repository = "https://github.com/aCursedComrade/sandbox-research"
license = "MIT"

[workspace.dependencies]
wdk = "0.2"
wdk-alloc = "0.2"
wdk-build = "0.2"
wdk-panic = "0.2"
wdk-sys = "0.2"
windows-sys = "0.52"
tonic = "0.11"
tonic-build = "0.11"
prost = "0.12"

[workspace.dependencies.tokio]
version = "1.35.1"
features = ["macros", "rt-multi-thread"]

# per-package panic,lto attributes are not supported yet
# https://doc.rust-lang.org/cargo/reference/profiles.html#overrides

[profile.dev]
lto = "off"
panic = "abort"
incremental = true

[profile.release]
lto = false
panic = "abort"
incremental = false
