[workspace]
resolver = "2"
members = ["frontend", "service"]

[workspace.package]
edition = "2021"
publish = false
repository = "https://github.com/aCursedComrade/sandbox-research"
license = "MIT"

[workspace.dependencies]
windows-sys = "0.52"
tonic = "0.11"
tonic-build = "0.11"
prost = "0.12"

[workspace.dependencies.tokio]
version = "1.35.1"
features = ["macros", "rt-multi-thread"]

[profile.dev]
lto = false

[profile.release]
lto = true
