[config]
default_to_workspace = false

[tasks.frontend]
description = "Builds the `frontend` crate"
command = "cargo"
args = ["build", "-p", "frontend"]

[tasks.service]
description = "Builds the `service` crate"
command = "cargo"
args = ["build", "-p", "service"]

[tasks.default]
# Dont do anything in the default task
clear = true
command = "cmd"
args = ["/c", "echo No default tasks is defined, look at Makefile.toml for available tasks"]
