[config]

[env.development]
RUST_LOG = "info"

# default available tasks not defined here:
# - print-env-flow
# - build-release
# - build
# - clean
# - test

[tasks.box_ui]
workspace = false
description = "Executes the `frontend` binary"
command = "cargo"
args = ["run", "--bin", "box_ui"]

[tasks.box_broker]
workspace = false
description = "Executes the `service` binary"
command = "cargo"
args = ["run", "--bin", "box_broker"]

[tasks.default]
dependencies = ["build"]
