[config]

[env.development]
RUST_LOG = "info"

# default available tasks not defined here:
# - print-env-flow
# - build-release
# - build
# - clean
# - test

[tasks.frontend]
workspace = false
description = "Executes the `frontend` binary"
command = "cargo"
args = ["run", "--bin", "boxui"]

[tasks.service]
workspace = false
description = "Executes the `service` binary"
command = "cargo"
args = ["run", "--bin", "boxbroker"]

[tasks.default]
dependencies = ["build"]
